apiVersion: v1
kind: Service
metadata:
  name: cdn-api
  namespace: cdn-system

spec:
  type: ClusterIP

  ports:
  - name: cdn-api
    port: 3000
    targetPort: cdn-api
  - name: cdn-api-debug
    port: 4000
    targetPort: cdn-api-debug
  - name: metrics
    port: 3001
    targetPort: metrics
  - name: prometheus
    port: 3002
    targetPort: prometheus
