apiVersion: v1
kind: Service
metadata:
  name: cdn-api
  namespace: cdn-system

spec:
  type: ClusterIP

  ports:
  - name: cdn-api
    port: 3330
    targetPort: cdn-api
  - name: cdn-api-debug
    port: 4440
    targetPort: cdn-api-debug
  - name: metrics
    port: 3331
    targetPort: metrics
  - name: prometheus
    port: 3332
    targetPort: prometheus
