apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cdn/
  - ./dev-cdn-configmap.yaml
patches:
  - path: ./dev-cdn-patch-deploy.yaml
  - path: ./dev-cdn-patch-service.yaml
images:
  - name: service-image
    newName: vergecloud/service/cdn-api
    newTag: 0.0.1
  - name: metrics-image
    newName: vergecloud/service/cdn-api-metrics
    newTag: 0.0.1
