apiVersion: v1
kind: Namespace
metadata:
  name: cdn-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn
  namespace: cdn-system

spec:
  selector:
    matchLabels:
      app: cdn

  template:
    metadata:
      labels:
        app: cdn

    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
      - name: init-migrate-seed
        image: service-image
        command: ['./cdn-admin', 'migrate-seed']
        env:
        - name: CDN_DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_user
              optional: true
        - name: CDN_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_password
              optional: true
        - name: CDN_DB_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_hostport
              optional: true
        - name: CDN_DB_DISABLE_TLS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_disabletls
              optional: true

      containers:
      - name: cdn-api
        image: service-image

        ports:
        - name: cdn-api
          containerPort: 3000
        - name: cdn-api-debug
          containerPort: 4000

        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /v1/readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /v1/liveness
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu

        - name: GOGC
          value: "off"

        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory

        - name: CDN_DB_USER # here as an example for configuring a hosted db.
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_user
              optional: true
        - name: CDN_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_password
              optional: true
        - name: CDN_DB_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_hostport
              optional: true
        - name: CDN_DB_DISABLE_TLS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_disabletls
              optional: true

        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

      - name: metrics
        image: metrics-image

        ports:
        - name: metrics
          containerPort: 3001
        - name: prometheus
          containerPort: 3002

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu

---

apiVersion: v1
kind: Service
metadata:
  name: cdn-api
  namespace: cdn-system

spec:
  selector:
    app: cdn
