apiVersion: v1
kind: Namespace
metadata:
  name: cdn-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: cdn-system
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      scrape_timeout: 10s # is set to the global default (10s).
    alerting:
    scrape_configs:
      - job_name: "cdn-api"
        metrics_path: '/metrics'
        scrape_interval: 5s
        scrape_timeout: 2s
        static_configs:
          - targets: [ "cdn-api.cdn-system.svc:3332" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: cdn-system
  labels:
    app: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.50.0
          args:
            - "--storage.tsdb.retention.time=1m"
            - "--config.file=/prom-conf/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
            - "--log.level=debug"
          ports:
            - name: prometheus
              containerPort: 9090
              hostPort: 9990
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 3750m
          volumeMounts:
            - name: config-volume
              mountPath: /prom-conf/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-conf
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cdn-system
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9990
      targetPort: prometheus
